
name: ACHIEVE-Service-CICD

on:
  push:
    branches:
      - '**'
    tags: 
      - 'dev_v*' 
      - 'uat_v*'  
      - 'qa_v*'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
          - DEV
          - QA
          - UAT

jobs:
  build-and-test:
    if: github.event_name != 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run chmod on setup.sh
        run: |
          if [ -f "$GITHUB_ACTION_PATH/setup.sh" ]; then
            chmod +x "$GITHUB_ACTION_PATH/setup.sh"
          fi

   

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x' 

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

